=== jfragosoperez/Jira/schemas/actor-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "self" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "actors" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "displayName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== jfragosoperez/Jira/examples/actor-example.json
{
  "self" : "http://www.example.com/jira/rest/api/2/project/MKY/role/10360" ,
  "name" : "Developers" ,
  "id" : 10360 ,
  "description" : "A project role that represents developers in a project" ,
  "actors" : [
    {
      "id" : 10240 ,
      "displayName" : "jira-developers" ,
      "type" : "atlassian-group-role-actor" ,
      "name" : "jira-developers"
    }
  ]
}
