=== jfragosoperez/Jira/schemas/componentViaPost-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "self" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "lead" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "avatarUrls" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "24x24" : {
              "type" : "string" ,
              "required" : false
            } ,
            "16x16" : {
              "type" : "string" ,
              "required" : false
            } ,
            "32x32" : {
              "type" : "string" ,
              "required" : false
            } ,
            "48x48" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "displayName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "active" : {
          "type" : "boolean" ,
          "required" : false
        }
      }
    } ,
    "assigneeType" : {
      "type" : "string" ,
      "required" : false
    } ,
    "assignee" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "avatarUrls" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "24x24" : {
              "type" : "string" ,
              "required" : false
            } ,
            "16x16" : {
              "type" : "string" ,
              "required" : false
            } ,
            "32x32" : {
              "type" : "string" ,
              "required" : false
            } ,
            "48x48" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "displayName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "active" : {
          "type" : "boolean" ,
          "required" : false
        }
      }
    } ,
    "realAssigneeType" : {
      "type" : "string" ,
      "required" : false
    } ,
    "realAssignee" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "avatarUrls" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "24x24" : {
              "type" : "string" ,
              "required" : false
            } ,
            "16x16" : {
              "type" : "string" ,
              "required" : false
            } ,
            "32x32" : {
              "type" : "string" ,
              "required" : false
            } ,
            "48x48" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "displayName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "active" : {
          "type" : "boolean" ,
          "required" : false
        }
      }
    } ,
    "isAssigneeTypeValid" : {
      "type" : "boolean" ,
      "required" : false
    }
  }
}

=== jfragosoperez/Jira/examples/component-example.json
{
  "self" : "http://www.example.com/jira/rest/api/2/component/10000" ,
  "id" : "10000" ,
  "name" : "Component 1" ,
  "description" : "This is a JIRA component" ,
  "lead" : {
    "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
    "name" : "fred" ,
    "avatarUrls" : {
      "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
      "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
      "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
      "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
    } ,
    "displayName" : "Fred F. User" ,
    "active" : false
  } ,
  "assigneeType" : "PROJECT_LEAD" ,
  "assignee" : {
    "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
    "name" : "fred" ,
    "avatarUrls" : {
      "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
      "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
      "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
      "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
    } ,
    "displayName" : "Fred F. User" ,
    "active" : false
  } ,
  "realAssigneeType" : "PROJECT_LEAD" ,
  "realAssignee" : {
    "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
    "name" : "fred" ,
    "avatarUrls" : {
      "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
      "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
      "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
      "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
    } ,
    "displayName" : "Fred F. User" ,
    "active" : false
  } ,
  "isAssigneeTypeValid" : false
}
