=== jfragosoperez/Jira/schemas/dashboards-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "startAt" : {
      "type" : "number" ,
      "required" : false
    } ,
    "maxResults" : {
      "type" : "number" ,
      "required" : false
    } ,
    "total" : {
      "type" : "number" ,
      "required" : false
    } ,
    "prev" : {
      "type" : "string" ,
      "required" : false
    } ,
    "next" : {
      "type" : "string" ,
      "required" : false
    } ,
    "dashboards" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "self" : {
              "type" : "string" ,
              "required" : false
            } ,
            "view" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== jfragosoperez/Jira/examples/dashboards-example.json
{
  "startAt" : 10 ,
  "maxResults" : 10 ,
  "total" : 143 ,
  "prev" : "http://www.example.com/jira/rest/api/2/dashboard?startAt=0" ,
  "next" : "http://www.example.com/jira/rest/api/2/dashboard?startAt=10" ,
  "dashboards" : [
    {
      "id" : "10000" ,
      "name" : "System Dashboard" ,
      "self" : "http://www.example.com/jira/rest/api/2/dashboard/10000" ,
      "view" : "http://www.example.com/jira/secure/Dashboard.jspa?selectPageId=10000"
    } , {
      "id" : "20000" ,
      "name" : "Build Engineering" ,
      "self" : "http://www.example.com/jira/rest/api/2/dashboard/20000" ,
      "view" : "http://www.example.com/jira/secure/Dashboard.jspa?selectPageId=20000"
    }
  ]
}
