=== jfragosoperez/Jira/schemas/filter-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "self" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "owner" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "avatarUrls" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "24x24" : {
              "type" : "string" ,
              "required" : false
            } ,
            "16x16" : {
              "type" : "string" ,
              "required" : false
            } ,
            "32x32" : {
              "type" : "string" ,
              "required" : false
            } ,
            "48x48" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "displayName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "active" : {
          "type" : "boolean" ,
          "required" : false
        }
      }
    } ,
    "jql" : {
      "type" : "string" ,
      "required" : false
    } ,
    "viewUrl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "searchUrl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "favourite" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "sharePermissions" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
      ]
    } ,
    "subscriptions" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "size" : {
          "type" : "number" ,
          "required" : false
        } ,
        "items" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
          ]
        } ,
        "max-results" : {
          "type" : "number" ,
          "required" : false
        } ,
        "start-index" : {
          "type" : "number" ,
          "required" : false
        } ,
        "end-index" : {
          "type" : "number" ,
          "required" : false
        }
      }
    }
  }
}

=== jfragosoperez/Jira/examples/filter-example.json
{
  "self" : "http://www.example.com/jira/rest/api/2/filter/10000" ,
  "id" : "10000" ,
  "name" : "All Open Bugs" ,
  "description" : "Lists all open bugs" ,
  "owner" : {
    "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
    "name" : "fred" ,
    "avatarUrls" : {
      "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
      "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
      "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
      "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
    } ,
    "displayName" : "Fred F. User" ,
    "active" : false
  } ,
  "jql" : "type = Bug and resolution is empty" ,
  "viewUrl" : "http://www.example.com/jira/secure/IssueNavigator.jspa?mode=hide&requestId=10000" ,
  "searchUrl" : "http://www.example.com/jira/rest/api/2/search?jql=type%20%3D%20Bug%20and%20resolutino%20is%20empty" ,
  "favourite" : true ,
  "sharePermissions" : [
  ] ,
  "subscriptions" : {
    "size" : 0 ,
    "items" : [
    ] ,
    "max-results" : 1000 ,
    "start-index" : 0 ,
    "end-index" : 0
  }
}

=== jfragosoperez/Jira/examples/filters-example.json
[
  {
    "self" : "http://www.example.com/jira/rest/api/2/filter/10000" ,
    "id" : "10000" ,
    "name" : "All Open Bugs" ,
    "description" : "Lists all open bugs" ,
    "owner" : {
      "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
      "name" : "fred" ,
      "avatarUrls" : {
        "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
        "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
        "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
        "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
      } ,
      "displayName" : "Fred F. User" ,
      "active" : false
    } ,
    "jql" : "type = Bug and resolution is empty" ,
    "viewUrl" : "http://www.example.com/jira/secure/IssueNavigator.jspa?mode=hide&requestId=10000" ,
    "searchUrl" : "http://www.example.com/jira/rest/api/2/search?jql=type%20%3D%20Bug%20and%20resolutino%20is%20empty" ,
    "favourite" : true ,
    "sharePermissions" : [
    ] ,
    "subscriptions" : {
      "size" : 0 ,
      "items" : [
      ] ,
      "max-results" : 1000 ,
      "start-index" : 0 ,
      "end-index" : 0
    }
  } , {
    "self" : "http://www.example.com/jira/rest/api/2/filter/10010" ,
    "id" : "10010" ,
    "name" : "My issues" ,
    "description" : "Issues assigned to me" ,
    "owner" : {
      "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
      "name" : "fred" ,
      "avatarUrls" : {
        "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
        "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
        "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
        "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
      } ,
      "displayName" : "Fred F. User" ,
      "active" : false
    } ,
    "jql" : "assignee = currentUser() and resolution is empty" ,
    "viewUrl" : "http://www.example.com/jira/secure/IssueNavigator.jspa?mode=hide&requestId=10010" ,
    "searchUrl" : "http://www.example.com/jira/rest/api/2/search?jql=assignee+%3D+currentUser%28%29+and+resolution+is+empty" ,
    "favourite" : true ,
    "sharePermissions" : [
      {
        "id" : 10000 ,
        "type" : "global"
      } , {
        "id" : 10010 ,
        "type" : "project" ,
        "project" : {
          "self" : "http://www.example.com/jira/rest/api/2/project/EX" ,
          "id" : "10000" ,
          "key" : "EX" ,
          "name" : "Example" ,
          "avatarUrls" : {
            "24x24" : "http://www.example.com/jira/secure/projectavatar?size=small&pid=10000" ,
            "16x16" : "http://www.example.com/jira/secure/projectavatar?size=xsmall&pid=10000" ,
            "32x32" : "http://www.example.com/jira/secure/projectavatar?size=medium&pid=10000" ,
            "48x48" : "http://www.example.com/jira/secure/projectavatar?size=large&pid=10000"
          }
        }
      }
    ] ,
    "subscriptions" : {
      "size" : 0 ,
      "items" : [
      ] ,
      "max-results" : 1000 ,
      "start-index" : 0 ,
      "end-index" : 0
    }
  }
]
