=== jfragosoperez/Jira/schemas/link-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "type" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "id" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "inward" : {
          "type" : "string" ,
          "required" : false
        } ,
        "outward" : {
          "type" : "string" ,
          "required" : false
        } ,
        "self" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "inwardIssue" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "id" : {
          "type" : "string" ,
          "required" : false
        } ,
        "key" : {
          "type" : "string" ,
          "required" : false
        } ,
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "fields" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "status" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "iconUrl" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "name" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          }
        }
      }
    } ,
    "outwardIssue" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "id" : {
          "type" : "string" ,
          "required" : false
        } ,
        "key" : {
          "type" : "string" ,
          "required" : false
        } ,
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "fields" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "status" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "iconUrl" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "name" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          }
        }
      }
    }
  }
}

=== jfragosoperez/Jira/examples/link-example.json
{
  "id" : "10001" ,
  "type" : {
    "id" : "1000" ,
    "name" : "Duplicate" ,
    "inward" : "Duplicated by" ,
    "outward" : "Duplicates" ,
    "self" : "http://www.example.com/jira/rest/api/2//issueLinkType/1000"
  } ,
  "inwardIssue" : {
    "id" : "10004" ,
    "key" : "PRJ-3" ,
    "self" : "http://www.example.com/jira/rest/api/2/issue/PRJ-3" ,
    "fields" : {
      "status" : {
        "iconUrl" : "http://www.example.com/jira//images/icons/statuses/open.png" ,
        "name" : "Open"
      }
    }
  } ,
  "outwardIssue" : {
    "id" : "10004L" ,
    "key" : "PRJ-2" ,
    "self" : "http://www.example.com/jira/rest/api/2/issue/PRJ-2" ,
    "fields" : {
      "status" : {
        "iconUrl" : "http://www.example.com/jira//images/icons/statuses/open.png" ,
        "name" : "Open"
      }
    }
  }
}
