=== jfragosoperez/Jira/schemas/notification-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "subject" : {
      "type" : "string" ,
      "required" : false
    } ,
    "textBody" : {
      "type" : "string" ,
      "required" : false
    } ,
    "htmlBody" : {
      "type" : "string" ,
      "required" : false
    } ,
    "to" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "reporter" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "assignee" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "watchers" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "voters" : {
          "type" : "boolean" ,
          "required" : false
        } ,
        "users" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "active" : {
                  "type" : "boolean" ,
                  "required" : false
                }
              }
            }
          ]
        } ,
        "groups" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "self" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        }
      }
    } ,
    "restrict" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "groups" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "self" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        } ,
        "permissions" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "id" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "key" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== jfragosoperez/Jira/examples/notification-example.json
{
  "subject" : "Duis eu justo eget augue iaculis fermentum." ,
  "textBody" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget venenatis elit. Duis eu justo eget augue iaculis fermentum. Sed semper quam laoreet nisi egestas at posuere augue semper." ,
  "htmlBody" : "Lorem ipsum <strong>dolor</strong> sit amet, consectetur adipiscing elit. Pellentesque eget venenatis elit. Duis eu justo eget augue iaculis fermentum. Sed semper quam laoreet nisi egestas at posuere augue semper." ,
  "to" : {
    "reporter" : false ,
    "assignee" : false ,
    "watchers" : true ,
    "voters" : true ,
    "users" : [
      {
        "name" : "fred" ,
        "active" : false
      }
    ] ,
    "groups" : [
      {
        "name" : "notification-group" ,
        "self" : "http://www.example.com/jira/rest/api/2/group?groupname=notification-group"
      }
    ]
  } ,
  "restrict" : {
    "groups" : [
      {
        "name" : "notification-group" ,
        "self" : "http://www.example.com/jira/rest/api/2/group?groupname=notification-group"
      }
    ] ,
    "permissions" : [
      {
        "id" : "10" ,
        "key" : "BROWSE"
      }
    ]
  }
}
