=== jfragosoperez/Jira/schemas/remoteVersionLinksReq-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "globalId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "myCustomLinkProperty" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "colors" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    } ,
    "notes" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    }
  }
}

=== jfragosoperez/Jira/examples/remoteVersionLinkReq-example.json
{
  "globalId" : "SomeGlobalId" ,
  "myCustomLinkProperty" : true ,
  "colors" : [
    "red" ,
    "green" ,
    "blue"
  ] ,
  "notes" : [
    "Remote version links may take any well-formed JSON shape that is desired," ,
    "provided that they fit within the maximum buffer size allowed," ,
    "which is currently 32,768 characters."
  ]
}
