=== jfragosoperez/Jira/schemas/serverInfo-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "baseUrl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "version" : {
      "type" : "string" ,
      "required" : false
    } ,
    "versionNumbers" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "number"
        }
      ]
    } ,
    "buildNumber" : {
      "type" : "number" ,
      "required" : false
    } ,
    "buildDate" : {
      "type" : "string" ,
      "required" : false
    } ,
    "serverTime" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scmInfo" : {
      "type" : "string" ,
      "required" : false
    } ,
    "buildPartnerName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "serverTitle" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== jfragosoperez/Jira/examples/serverInfo-example.json
{
  "baseUrl" : "http://localhost:8080/jira" ,
  "version" : "5.0-SNAPSHOT" ,
  "versionNumbers" : [
    5 ,
    0 ,
    0
  ] ,
  "buildNumber" : 582 ,
  "buildDate" : "2014-06-11T07:33:41.458+0000" ,
  "serverTime" : "2014-06-11T07:33:41.458+0000" ,
  "scmInfo" : "1f51473f5c7b75c1a69a0090f4832cdc5053702a" ,
  "buildPartnerName" : "Example Partner Co." ,
  "serverTitle" : "My Shiny New JIRA Server"
}
