=== jfragosoperez/Jira/schemas/user-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "self" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "emailAddress" : {
      "type" : "string" ,
      "required" : false
    } ,
    "avatarUrls" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "24x24" : {
          "type" : "string" ,
          "required" : false
        } ,
        "16x16" : {
          "type" : "string" ,
          "required" : false
        } ,
        "32x32" : {
          "type" : "string" ,
          "required" : false
        } ,
        "48x48" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "displayName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "active" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "timeZone" : {
      "type" : "string" ,
      "required" : false
    } ,
    "groups" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "size" : {
          "type" : "number" ,
          "required" : false
        } ,
        "items" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "self" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        }
      }
    } ,
    "expand" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== jfragosoperez/Jira/examples/user-example.json
{
  "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
  "name" : "fred" ,
  "emailAddress" : "fred@example.com" ,
  "avatarUrls" : {
    "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
    "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
    "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
    "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
  } ,
  "displayName" : "Fred F. User" ,
  "active" : true ,
  "timeZone" : "Australia/Sydney" ,
  "groups" : {
    "size" : 3 ,
    "items" : [
      {
        "name" : "jira-user" ,
        "self" : "http://www.example.com/jira/rest/api/2/group?groupname=jira-user"
      } , {
        "name" : "jira-admin" ,
        "self" : "http://www.example.com/jira/rest/api/2/group?groupname=jira-admin"
      } , {
        "name" : "important" ,
        "self" : "http://www.example.com/jira/rest/api/2/group?groupname=important"
      }
    ]
  } ,
  "expand" : "groups"
}
