=== jfragosoperez/Jira/schemas/voters-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "self" : {
      "type" : "string" ,
      "required" : false
    } ,
    "votes" : {
      "type" : "number" ,
      "required" : false
    } ,
    "hasVoted" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "voters" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "self" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "avatarUrls" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "24x24" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "16x16" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "32x32" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "48x48" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "displayName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "active" : {
              "type" : "boolean" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== jfragosoperez/Jira/examples/voters-example.json
{
  "self" : "http://www.example.com/jira/rest/api/issue/MKY-1/votes" ,
  "votes" : 24 ,
  "hasVoted" : true ,
  "voters" : [
    {
      "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
      "name" : "fred" ,
      "avatarUrls" : {
        "24x24" : "http://www.example.com/jira/secure/useravatar?size=small&ownerId=fred" ,
        "16x16" : "http://www.example.com/jira/secure/useravatar?size=xsmall&ownerId=fred" ,
        "32x32" : "http://www.example.com/jira/secure/useravatar?size=medium&ownerId=fred" ,
        "48x48" : "http://www.example.com/jira/secure/useravatar?size=large&ownerId=fred"
      } ,
      "displayName" : "Fred F. User" ,
      "active" : false
    }
  ]
}
