=== jfragosoperez/Jira/schemas/worklog-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "self" : {
      "type" : "string" ,
      "required" : false
    } ,
    "author" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "displayName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "active" : {
          "type" : "boolean" ,
          "required" : false
        }
      }
    } ,
    "updateAuthor" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "self" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "displayName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "active" : {
          "type" : "boolean" ,
          "required" : false
        }
      }
    } ,
    "comment" : {
      "type" : "string" ,
      "required" : false
    } ,
    "visibility" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "type" : {
          "type" : "string" ,
          "required" : false
        } ,
        "value" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "started" : {
      "type" : "string" ,
      "required" : false
    } ,
    "timeSpent" : {
      "type" : "string" ,
      "required" : false
    } ,
    "timeSpentSeconds" : {
      "type" : "number" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== jfragosoperez/Jira/examples/worklog-example.json
{
  "self" : "http://www.example.com/jira/rest/api/2/issue/10010/worklog/10000" ,
  "author" : {
    "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
    "name" : "fred" ,
    "displayName" : "Fred F. User" ,
    "active" : false
  } ,
  "updateAuthor" : {
    "self" : "http://www.example.com/jira/rest/api/2/user?username=fred" ,
    "name" : "fred" ,
    "displayName" : "Fred F. User" ,
    "active" : false
  } ,
  "comment" : "I did some work here." ,
  "visibility" : {
    "type" : "group" ,
    "value" : "jira-developers"
  } ,
  "started" : "2014-05-27T08:32:06.865+0000" ,
  "timeSpent" : "3h 20m" ,
  "timeSpentSeconds" : 12000 ,
  "id" : "100028"
}
