=== jfragosoperez/Jira/schemas/workflowscheme-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "defaultWorkflow" : {
      "type" : "string" ,
      "required" : false
    } ,
    "issueTypeMappings" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "IsueTypeId2" : {
          "type" : "string" ,
          "required" : false
        } ,
        "IsueTypeId" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "draft" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "self" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== jfragosoperez/Jira/examples/workflowscheme-example.json
{
  "id" : 101010 ,
  "name" : "Workflow Scheme One" ,
  "description" : "Workflow Scheme One Description" ,
  "defaultWorkflow" : "DefaultWorkflowName" ,
  "issueTypeMappings" : {
    "IsueTypeId2" : "WorkflowName" ,
    "IsueTypeId" : "WorkflowName"
  } ,
  "draft" : false ,
  "self" : "http://www.example.com/jira/rest/api/2/workflowscheme/101010"
}
